
on:
  push:

jobs:
  
  build-and-upload:
    strategy:
      fail-fast: true
      matrix:
        os:
        - ubuntu-latest
        - macos-13
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Stack
        if: matrix.os == 'macos-13'
        run: |
          curl -sSL https://get.haskellstack.org | sh

      - name: Build and test with Stack
        run: |
          stack build
          cp $(stack path --dist-dir)/build/stack/stack stack-${{ runner.os }}
          #stack test

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stack-${{ runner.os }}
          path: stack-${{ runner.os }}
          if-no-files-found: error
